env:
  browser: true
  commonjs: true
  es2021: true
extends: "eslint:recommended"
parserOptions:
  ecmaVersion: 12
rules: { "semi": "error" }
ignorePatterns: ["custom/**/*.js", "dist/**/*.js", "lib/datalog.js"]
overrides:
  [
    {
      files: ["lib/extension.js", "webpack.config.js"],
      rules: { "no-undef": "off" },
    },
  ]
