env:
  browser: true
  commonjs: true
  es2021: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 12
rules: {
  "semi": "error"
}
overrides: [
    {
      files: ["lib/extension.js"],
      rules: {
        "no-undef": "off"
      }
    }
]
