repos:
  - repo: git@github.com:pre-commit/mirrors-yapf.git
    rev: v0.30.0
    hooks:
      - id: yapf
        args: ['--style=.style.yapf', '--parallel', '--in-place']
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.3
    hooks:
      - id: flake8
