name: Lint js files

on:
  push:
    paths:
      - "**.js"
    branches:
      - master
      - github_workflows
  pull_request:
    branches:
      - master

jobs:
  js_linter:
    runs-on: ubuntu-latest
    container:
      image: python:3.8.2-slim-buster
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install dependencies
        run: |
          cd js
          npm install eslint
      - name: Run eslint
        run: npx eslint .
