name: Lint python and js files

on:
  push:
    branches:
      - master
      - github_workflows
  pull_request:
    branches:
      - master

jobs:
  python_linter:
    runs-on: ubuntu-latest
    container:
      image: python:3.8.2-slim-buster
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Run flake8
        run: |
          flake8

  js_linter:
    runs-on: ubuntu-latest
    container:
      image: python:3.8.2-slim-buster
    steps:
      - uses: actions/checkout@v2
      - name Use Node.js
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install dependencies
        run: npm install eslint
      - name: Run eslint
        run: |
          cd js
          eslint
