name: Lint python files

on:
  push:
    paths:
      - "**.py"
    branches:
      - master
      - github_workflows
  pull_request:
    branches:
      - master

jobs:
  python_linter:
    runs-on: ubuntu-latest
    container:
      image: python:3.8.2-slim-buster
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Run flake8
        run: |
          flake8
