name: Trigger test on neurolang_web

on:
  push:
    branches:
      - master
      - github_workflows

jobs:
  trigger_test_on_neurolang_web:
    runs-on: ubuntu-latest
    steps:
      - name: Post request to neurolang_web
        run: |
          curl \
          -XPOST -u "token:${{ secrets.CI_TRIGGER_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/NeuroLang/neurolang_web/dispatches \
          -d '{"event_type":"neurolang-ipywidgets"}'
